---
# This workflow pip install's the compiler_gym package and checks that the
# module can be imported.
#
# The goal of this workflow is to catch failures in the installation process
# that can occur because of a breaking change in the dependent packages, and to
# test for any import-time error.
name: Pip install test

on:
    workflow_dispatch:
    schedule:
        - cron: 0 0 * * *  # daily

jobs:
    test:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                python: [3.6, 3.7, 3.8, 3.9]

        steps:
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}

            - name: Install python wheel
              # We use the TestPyPI repository to install the compiler_gym
              # package from because we use the install count on the main
              # repository to track growth and usage of the project. We also
              # provide the main PyPI repo as a fallback for installing
              # dependencies.
              run: python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ compiler_gym

            - name: Check package version
              run: python -c 'import compiler_gym; print(compiler_gym.__version__)'
